// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7zYn6c6mxn54Cx4SmC6Inihi7n7U-O7I',
    appId: '1:94045723797:web:ea632b296c845203c0cf9c',
    messagingSenderId: '94045723797',
    projectId: 'fir-app-01-11df4',
    authDomain: 'fir-app-01-11df4.firebaseapp.com',
    storageBucket: 'fir-app-01-11df4.firebasestorage.app',
    measurementId: 'G-6BQ73ZC6VW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlHnCQZO3NbOmslCZrT5QlW0tfreIIhFc',
    appId: '1:94045723797:android:d0da2fa3f2f91ae9c0cf9c',
    messagingSenderId: '94045723797',
    projectId: 'fir-app-01-11df4',
    storageBucket: 'fir-app-01-11df4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhR9OwsXRc098_qgrntpKTN_hN-Xu9sis',
    appId: '1:94045723797:ios:b65040ac39213a1bc0cf9c',
    messagingSenderId: '94045723797',
    projectId: 'fir-app-01-11df4',
    storageBucket: 'fir-app-01-11df4.firebasestorage.app',
    iosBundleId: 'com.example.appFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhR9OwsXRc098_qgrntpKTN_hN-Xu9sis',
    appId: '1:94045723797:ios:b65040ac39213a1bc0cf9c',
    messagingSenderId: '94045723797',
    projectId: 'fir-app-01-11df4',
    storageBucket: 'fir-app-01-11df4.firebasestorage.app',
    iosBundleId: 'com.example.appFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7zYn6c6mxn54Cx4SmC6Inihi7n7U-O7I',
    appId: '1:94045723797:web:02779bd05552f66fc0cf9c',
    messagingSenderId: '94045723797',
    projectId: 'fir-app-01-11df4',
    authDomain: 'fir-app-01-11df4.firebaseapp.com',
    storageBucket: 'fir-app-01-11df4.firebasestorage.app',
    measurementId: 'G-R8PPRLKDBS',
  );
}
